name: PR Verification

on:
    pull_request:

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

            - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version-file: package.json
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm test
